version: "3"

services:

  # Бот-загрузчик видео
  yt_dwn_bot:
    build: yt_dwn_bot/
    command: ./yt_dwn_bot
    restart: always
    volumes:
      - /opt/yt_dwn_bot:/opt
      - /opt/yt_dwn_bot/libvosk.so:/usr/lib/libvosk.so
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Moscow"

  # Бот Алины Польской
  diptok_pochta_bot:
    build: diptok_pochta_bot/
    command: ./diptok_pochta_bot
    restart: always
    volumes:
      - /opt/diptok_pochta_bot:/opt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Moscow"

  # Бот-генератор паролей
  pmake_bot:
    build: pmake_bot/
    command: ./pmake_bot
    restart: always
    volumes:
      - /opt/pmake_bot:/opt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Moscow"

  # Волчий бот
  serious_wolf_bot:
    build: serious_wolf_bot/
    command: ./serious_wolf_bot
    restart: always
    volumes:
      - /opt/serious_wolf_bot:/opt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Moscow"

