version: "3"

services:

  pmake_bot:
    build: pmake_bot/
    command: ./pmake_bot
    volumes:
      - /opt/pmake_bot:/opt

  serious_wolf_bot:
    build: serious_wolf_bot/
    command: ./serious_wolf_bot
    volumes:
      - /opt/serious_wolf_bot:/opt
