version: "3"

services:

  # Бот Алины Польской
  diptok_pochta_bot:
    build: diptok_pochta_bot/
    command: ./diptok_pochta_bot
    restart: always
    volumes:
      - /opt/diptok_pochta_bot:/opt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Moscow"

  # Бот-генератор паролей
  pmake_bot:
    build: pmake_bot/
    command: ./pmake_bot
    restart: always
    volumes:
      - /opt/pmake_bot:/opt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Moscow"

