version: "3"

services:

  yt_dwn_bot:
    container_name: yt_dwn_bot
    image: 192.168.88.206:5000/yt_dwn_bot:latest
    command: ./yt_dwn_bot
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      - /mnt/sata1:/media

      - /opt/yt_dwn_bot/Logs:/app/Logs
      - /opt/yt_dwn_bot/history:/app/history
      - /opt/yt_dwn_bot/vosk_models:/app/vosk_models

      - /opt/yt_dwn_bot/config.ini:/app/config.ini
      - /opt/yt_dwn_bot/cookie_dummy.txt:/app/cookie_dummy.txt

    ports:
      - '30001:30000'
    environment:
      TZ: "Europe/Moscow"

